services:
  s3-migration-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s3-migration-scheduler
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:5000
    volumes:
      # Persist database and logs
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - s3-migration-network

networks:
  s3-migration-network:
    driver: bridge

volumes:
  data:
  logs:
